### ISSUE TITLE
I cannot add input devices.

### ISSUE THREAD

**Issue by ghost** [Snoothy/UCR#155]
I installed Interception Сore according to the instructions, but it doesn't work. I don't have a list of input devices displayed. Maybe I'm doing something wrong? Please help.

P.S. Sorry for the mistakes, my English is not good.
![5n5Zv3OmAI](https://user-images.githubusercontent.com/62849465/77863026-ffda2980-7227-11ea-9f7e-836e4342cf84.png)

**Comment by PortableGoogle** [comment]
did you download the provider separately then find the exe file, and run an admin elevated command prompt to install it?

**Comment by WelpThatWorked** [comment]
Reference https://github.com/Snoothy/UCR/wiki/Core-Providers, choose the input/output devices you would like, and click the links to find instructions on how to set them up.

**Comment by Flightofbird** [comment]
I have the same issue, I had UCR working fine showing my input devices, after setup I noticed UCR wasn't blocking my keyboard inputs, so after some research I installed interception through the command line, and now after a UCR re-unzip all my input devices are gone.

I have a feeling interception didn't install correctly because after typing install-interception.exe /install I got no response (cmd went back to my directory) which usually means it worked, but the wiki says it should output "Interception successfully installed"

**Comment by Flightofbird** [comment]
Not sure what fixed it but after uninstalling everything reinstalling rebooting I see my inputs now. I still can't get Interception to block my keyboard inputs, despite settings value set to "true"
Edit:
Found solution at #62 downgrading to v0.7.0 is a temporary fix

**Comment by tonymichael00** [comment]
I also am not getting input with interception

**Comment by tonymichael00** [comment]
redownloading ucr worked

**Comment by Snoothy** [comment]
Missing input devices are usually due to blocked files or missing setup of specific providers. Try to run the unblocker in the UCR folder and follow the installation guide: https://github.com/Snoothy/UCR/wiki/Installation-and-Setup
