### ISSUE TITLE
Analog input filtering/dampening

### ISSUE THREAD

**Issue by swift502** [Snoothy/UCR#37]
Hi, love this program. (And it's AHK predecessors...)

I'd love to implement dampening filters to smooth out movements done with analog sticks on a controller. DIRT Rally's default steering smoothing is ridiculously strong, but raw input isn't ideal for driving either. I'm thinking of a [damped spring filter](https://jsfiddle.net/bkanber/pDngH) with a few variables for start, but I'm sure there are different algorithms for this purpose if the spring based one wasn't very good...

Would it be just another plugin?
Thanks.

**Comment by evilC** [comment]
Whatever way you want to do it, something running at a timed interval seems reasonable in this instance, but you would want to be sure to stop the timer when the plugin DeActivates etc.  
At the moment, plugins are all in one file, but we intend to make each plugin it's own DLL, so what you do in your own plugins would be your own business :)
BTW, if you want to discuss stuff, best place is the Discord channel rather than the issue tracker...

**Comment by swift502** [comment]
Thanks! I'll create a PR.
