### ISSUE TITLE
F13 - F14 Rebinding Error

### ISSUE THREAD

**Issue by archit9169** [Snoothy/UCR#83]
I noticed that when i rebind f13, it binds it as tab. And other like f14 etc are not shown.

**Comment by evilC** [comment]
What device do you have that sends F13?

**Comment by Xyaren** [comment]
Worked in "old" UCR: 

![image](https://user-images.githubusercontent.com/5864045/53268025-41bfa480-36e5-11e9-9771-8dfdb0bd5c98.png)

Very usefull to have those so you donÄt need to reuse other keys or create complex hotkeys in games.

**Comment by archit9169** [comment]
I have a gaming mouse which also acts as a virtual keyboard. And it can send f13 and others if i remap them via autohotinterception.

Not that most games recognise these keys. I was just messing with stuff and testing the capabilities of ucr.

**Comment by evilC** [comment]
OK, I tracked this one down.  
The reason was that the Windows function (GetKeyNameTextW) to get key names from Scan Code does not work for F13-F24, so I had to create a lookup table for them :(  
I also ported in some other fixes from AutoHotInterception (Fixes for more keys).  
[this](https://github.com/Snoothy/UCR/files/2933256/Core_Interception.zip) replacement DLL should fix it until we make a new release

**Comment by Snoothy** [comment]
This should be fixed in v0.9.0
